services:
  - type: web
    name: shop-api
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /swagger
